import React from "react";
import { Header } from "../header";
import Head from "next/head";

type LayoutProps = {
  children?: React.ReactNode;
};
const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>REST Countries API with color theme switcher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="pb-11">
        <Header />
        {children}
      </main>
    </>
  );
};

export { Layout };
